/**
 * Shared AI letter disclaimer — required on ALL AI-generated letters.
 * Must appear in: letter text output, PDF exports, frontend display, and email exports.
 */

/** Plain text disclaimer appended to generated letter content */
export const AI_LETTER_DISCLAIMER =
  '\n\n---\nThis letter was generated by AI using publicly available legal information. It does not constitute legal advice. If unsure, consult a qualified solicitor or Citizens Advice.';

/** HTML disclaimer for PDF and web display */
export const AI_LETTER_DISCLAIMER_HTML =
  'This letter was generated with AI assistance using publicly available legal information from legislation.gov.uk. It does not constitute legal advice. If you are unsure about your rights, please consult a qualified solicitor, Citizens Advice (citizensadvice.org.uk), or your relevant ombudsman.';
