import type { Metadata } from 'next';
import { MarkNav, MarkFoot } from '../blog/_shared';
import CheckClient from './CheckClient';
import '../blog/styles.css';

/**
 * /check — the free, public, no-account case checker.
 *
 * This is the top of the acquisition funnel. A visitor can pick a
 * category, describe their problem, and get a case strength assessment,
 * the verified UK law that applies with a link to each official source,
 * the escalation route, and a complete draft letter, without creating an
 * account or handing over an email address.
 *
 * Server component so the route owns its metadata and JSON-LD. The
 * interactive wizard is the client component in ./CheckClient.tsx and
 * all analysis happens server-side in /api/check.
 *
 * SEO rules observed here: no outcome claims, no success rates, no
 * "guaranteed" anywhere, and the not-a-law-firm disclaimer follows the
 * same pattern as the rest of the marketing surface.
 */

const TITLE = 'Free UK case check: how strong is your complaint? | Paybacker';
const DESCRIPTION =
  'Describe your UK consumer problem and see how strong your case looks, which UK laws and regulator rules apply with a link to every official source, and a complete draft complaint letter. Free, no account, no email required.';

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: 'https://paybacker.co.uk/check' },
  keywords: [
    'check my consumer case UK',
    'free complaint letter UK',
    'UK consumer rights checker',
    'mid contract price rise rights',
    'energy bill dispute UK',
    'flight delay compensation UK',
  ],
  openGraph: {
    title: 'Check your case against the actual UK law. Free, no account.',
    description:
      'See how strong your complaint looks, which UK statutes and regulator rules apply with a link to every official source, and a full draft letter. No sign-up needed.',
    url: 'https://paybacker.co.uk/check',
    siteName: 'Paybacker',
    type: 'website',
    locale: 'en_GB',
  },
  twitter: {
    card: 'summary',
    title: 'Check your case against the actual UK law. Free, no account.',
    description:
      'Case strength, the exact rules that apply with official sources, and a full draft letter. Free to read and copy.',
  },
};

const JSON_LD = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebApplication',
      name: 'Paybacker case check',
      url: 'https://paybacker.co.uk/check',
      applicationCategory: 'BusinessApplication',
      operatingSystem: 'Any',
      description: DESCRIPTION,
      inLanguage: 'en-GB',
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'GBP',
        description: 'Free to use. No account required to see the assessment, the citations or the draft letter.',
      },
      publisher: {
        '@type': 'Organization',
        name: 'Paybacker LTD',
        url: 'https://paybacker.co.uk',
      },
    },
    {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Paybacker', item: 'https://paybacker.co.uk' },
        { '@type': 'ListItem', position: 2, name: 'Free case check', item: 'https://paybacker.co.uk/check' },
      ],
    },
    {
      '@type': 'FAQPage',
      mainEntity: [
        {
          '@type': 'Question',
          name: 'Do I need an account to use the case check?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'No. The case strength assessment, the UK laws that apply with a link to each official source, the escalation route and the full draft letter are all free to read and copy without an account or an email address.',
          },
        },
        {
          '@type': 'Question',
          name: 'Where do the legal citations come from?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'They are retrieved from a maintained index of UK legislation, regulator rules and official guidance, not generated by an AI model. Every source URL is checked against an allowlist of official domains such as legislation.gov.uk, ofcom.org.uk, ofgem.gov.uk and fca.org.uk before it is shown. Anything from a trade body, law firm blog, news site or aggregator is dropped. Where we hold no verified citation for a case we say so rather than inventing one.',
          },
        },
        {
          '@type': 'Question',
          name: 'What does the case strength score mean?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'It measures how well-evidenced and legally grounded your complaint is, based on whether we hold verified law for the category, whether the provider is named, whether the amount is known, whether the problem is inside the relevant time limit, how much supporting evidence you hold, and whether the provider has been given a chance to put it right. It is not a prediction of the outcome and no result is guaranteed.',
          },
        },
        {
          '@type': 'Question',
          name: 'Is Paybacker a law firm?',
          acceptedAnswer: {
            '@type': 'Answer',
            text: 'No. Paybacker helps you exercise your own rights under UK consumer law and drafts correspondence on your behalf. It is not legal advice. For disputes over £5,000, court proceedings, or facts unique to your situation, speak to a qualified solicitor or Citizens Advice.',
          },
        },
      ],
    },
  ],
};

export default function CheckPage() {
  return (
    <div className="m-blog-root">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
      />
      <MarkNav />
      <CheckClient />
      <MarkFoot />
    </div>
  );
}
