/**
 * Build an Ombudsman escalation pack for a dispute.
 *
 * Three deliverables, all real:
 *
 *   1. A referral letter addressed to the relevant ombudsman / ADR body,
 *      generated by the existing `generateComplaintLetter` engine with
 *      `letterType: 'ombudsman_escalation'`. That is a one-key addition to
 *      the engine's internal LETTER_TYPE_CONTEXT map — no signature
 *      change, no new `voice`, so both the consumer and B2B call sites of
 *      the shared engine are untouched (CLAUDE.md: `generateComplaintLetter`
 *      is the only shared helper; additive changes only).
 *
 *   2. An evidence bundle assembled from the dispute's `correspondence`
 *      rows in chronological order, numbered so the letter can cite
 *      "Exhibit 3" and the reader can find it.
 *
 *   3. Deadline tracking. This also backfills `disputes.fca_8_week_deadline`,
 *      a column that the 20260501100000 migration created but which NO
 *      code path has ever written — meaning Rule 4 of the Dispute Agent
 *      state machine (escalate when the 8-week clock expires) could never
 *      fire in production. Generating a pack now populates it.
 *
 * ==================== A NOTE ON DEADLINE CORRECTNESS ====================
 * Referral windows differ by scheme: the Financial Ombudsman gives six
 * months from the firm's final response, the Energy Ombudsman twelve
 * months, and the CAA's ADR schemes differ again. Rather than encode a
 * number we would have to keep correct across every sector, this module:
 *
 *   - computes `eligibleFrom` as first-contact + 8 weeks, which is the
 *     well-established mechanical point at which most UK schemes will
 *     accept a case without the company's agreement; and
 *   - computes `actByReminder` conservatively as eligibleFrom + 6 months,
 *     the SHORTEST common window, purely as an internal reminder date; and
 *   - surfaces `route.timeLimit` verbatim from the vetted
 *     `SECTOR_GUIDANCE` table as the authoritative statement of the limit.
 *
 * The authoritative text always wins in the UI. `actByReminder` must never
 * be presented as "your deadline" — it is when we nudge, deliberately
 * early. This follows the CLAUDE.md compliance principle: where we cannot
 * be certain, we do not assert.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { generateComplaintLetter } from '@/lib/agents/complaints-agent';
import { resolveOmbudsman, type OmbudsmanRouting } from '@/lib/escalation-pack/ombudsman';

const EIGHT_WEEKS_MS = 56 * 24 * 60 * 60 * 1000;
const SIX_MONTHS_MS = 182 * 24 * 60 * 60 * 1000;

/** Correspondence entry types that count as evidence, in display order. */
const EVIDENCE_TYPE_LABEL: Record<string, string> = {
  ai_letter: 'Letter sent to the company',
  company_email: 'Email received from the company',
  company_letter: 'Letter received from the company',
  company_response: 'Response from the company',
  phone_call: 'Note of a telephone call',
  user_note: 'Your own note',
};

export interface EvidenceItem {
  seq: number;
  entry_type: string;
  label: string;
  title: string | null;
  dated: string | null;
  summary: string | null;
  content: string;
  attachment_count: number;
}

export interface BuiltPack {
  sectorKey: string | null;
  routing: OmbudsmanRouting;
  escalationLetter: string;
  legalReferences: string[];
  nextSteps: string[];
  evidencePack: EvidenceItem[];
  eligibleFrom: string | null;
  actByReminder: string | null;
  model: string;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Dispute = Record<string, any>;

/**
 * Pull the dispute's correspondence and turn it into a numbered bundle.
 *
 * Content is truncated per item so a 40-message thread cannot blow the
 * row size or the model's context. The full text always remains in
 * `correspondence` — this is a presentation bundle, not the system of
 * record.
 */
export async function buildEvidencePack(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: SupabaseClient<any, any, any>,
  disputeId: string,
  userId: string,
): Promise<EvidenceItem[]> {
  const { data } = await supabase
    .from('correspondence')
    .select('id, entry_type, title, content, summary, attachments, entry_date, created_at')
    .eq('dispute_id', disputeId)
    .eq('user_id', userId)
    .order('entry_date', { ascending: true, nullsFirst: false })
    .order('created_at', { ascending: true })
    .limit(60);

  return (data ?? []).map((row: Dispute, i: number) => ({
    seq: i + 1,
    entry_type: row.entry_type,
    label: EVIDENCE_TYPE_LABEL[row.entry_type] ?? 'Correspondence',
    title: row.title ?? null,
    dated: row.entry_date ?? row.created_at ?? null,
    summary: row.summary ?? null,
    content: typeof row.content === 'string' ? row.content.slice(0, 8000) : '',
    attachment_count: Array.isArray(row.attachments) ? row.attachments.length : 0,
  }));
}

/** Compact the bundle into prose the letter generator can reason over. */
function evidenceToThreadContext(items: EvidenceItem[]): string {
  if (items.length === 0) return '';
  const lines = items.map((item) => {
    const date = item.dated
      ? new Date(item.dated).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
      : 'undated';
    const body = (item.summary || item.content).slice(0, 900);
    return `Exhibit ${item.seq} — ${item.label}, ${date}${item.title ? ` ("${item.title}")` : ''}:\n${body}`;
  });
  return `\nCORRESPONDENCE BUNDLE (cite these as "Exhibit N" in the letter — the reader has them attached in this order):\n${lines.join('\n\n')}\n`;
}

/**
 * Compute the escalation clock.
 *
 * `first_letter_sent_at` is the correct anchor when present. Falling back
 * to `created_at` is deliberately conservative in the user's favour: it
 * can only make the eligibility date EARLIER, never later, and the pack
 * always shows the authoritative scheme text alongside.
 */
export function computeDeadlines(dispute: Dispute): { eligibleFrom: string | null; actByReminder: string | null } {
  const anchorRaw = dispute.first_letter_sent_at || dispute.created_at;
  if (!anchorRaw) return { eligibleFrom: null, actByReminder: null };

  const anchor = new Date(anchorRaw).getTime();
  if (Number.isNaN(anchor)) return { eligibleFrom: null, actByReminder: null };

  const eligible = anchor + EIGHT_WEEKS_MS;
  return {
    eligibleFrom: new Date(eligible).toISOString(),
    actByReminder: new Date(eligible + SIX_MONTHS_MS).toISOString(),
  };
}

/**
 * Generate the full pack. Does not persist — the caller writes the row so
 * it controls entitlement redemption ordering.
 */
export async function buildEscalationPack(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: SupabaseClient<any, any, any>,
  dispute: Dispute,
  userId: string,
): Promise<BuiltPack> {
  const routing = resolveOmbudsman({
    issueType: dispute.issue_type,
    disputeType: dispute.dispute_type,
    merchantIndustry: dispute.merchant_industry,
    providerType: dispute.provider_type,
    providerName: dispute.provider_name,
    issueSummary: dispute.issue_summary,
  });

  const evidencePack = await buildEvidencePack(supabase, dispute.id, userId);
  const { eligibleFrom, actByReminder } = computeDeadlines(dispute);

  const providerName: string = dispute.provider_name ?? 'the company';
  const amount = dispute.disputed_amount ?? dispute.recovered_amount_gbp ?? null;

  // Sector-specific points and deadline text, fed in as prose so the
  // model has the vetted SECTOR_GUIDANCE content rather than its own
  // recollection of the scheme rules.
  const sectorBrief = [
    routing.sectorLabel ? `Sector: ${routing.sectorLabel}.` : '',
    `Escalation body: ${routing.route.name} (${routing.route.url}).`,
    `Eligibility: ${routing.route.eligibility}`,
    `Time limit: ${routing.route.timeLimit}`,
    `Cost to the consumer: ${routing.route.cost}`,
    `Whether the outcome binds the company: ${routing.route.binding}`,
    routing.deadlines.length
      ? `Sector deadlines:\n${routing.deadlines.map((d) => `- ${d.title}: ${d.body}`).join('\n')}`
      : '',
    routing.letterPoints.length
      ? `Points this sector's complaints handlers respond to:\n${routing.letterPoints.map((p) => `- ${p}`).join('\n')}`
      : '',
  ].filter(Boolean).join('\n');

  const issueDescription = [
    `The consumer is referring an unresolved dispute with ${providerName} to ${routing.route.name}.`,
    dispute.issue_summary ? `Original complaint: ${dispute.issue_summary}` : '',
    `The company has not resolved the complaint. ${
      eligibleFrom && new Date(eligibleFrom) <= new Date()
        ? 'More than eight weeks have passed since the complaint was first raised.'
        : 'The eight-week period is still running; the letter must say so and note that it should be treated as a referral once the company issues a deadlock letter or the period expires.'
    }`,
    '',
    'VETTED SCHEME INFORMATION — use this and do not substitute your own recollection of the scheme rules:',
    sectorBrief,
  ].filter(Boolean).join('\n');

  const generated = await generateComplaintLetter({
    // The addressee. The engine's consumer voice writes TO `companyName`,
    // so passing the ombudsman here produces a letter addressed to the
    // scheme rather than to the merchant.
    companyName: routing.route.name,
    letterType: 'ombudsman_escalation',
    issueDescription,
    desiredOutcome: dispute.desired_outcome
      || 'A full refund of the disputed amount and a decision that the company acted unfairly.',
    amount: amount ? String(amount) : undefined,
    accountNumber: dispute.account_number ?? undefined,
    incidentDate: dispute.transaction_date ?? undefined,
    previousContact: dispute.first_letter_sent_at
      ? `The consumer first wrote to ${providerName} on ${new Date(dispute.first_letter_sent_at).toLocaleDateString('en-GB')}. ${dispute.reminder_count ? `${dispute.reminder_count} chaser(s) have been sent since.` : 'No substantive resolution has been offered.'}`
      : undefined,
    threadContext: evidenceToThreadContext(evidencePack),
  });

  return {
    sectorKey: routing.sectorKey,
    routing,
    escalationLetter: generated.letter,
    legalReferences: generated.legalReferences ?? [],
    nextSteps: generated.nextSteps ?? [],
    evidencePack,
    eligibleFrom,
    actByReminder,
    model: 'claude-sonnet-4-6',
  };
}
