'use client';

export const dynamic = 'force-dynamic';
export const runtime = 'edge';

import { useState } from 'react';
import { CreditCard, Calendar, TrendingDown, X, Mail, Copy, CheckCircle } from 'lucide-react';

interface Subscription {
  id: string;
  name: string;
  provider: string;
  amount: number;
  billingCycle: 'monthly' | 'yearly';
  nextBillingDate: string;
  category: string;
  lastUsed: string | null;
  status: 'active' | 'pending_cancel' | 'cancelled';
}

const mockSubscriptions: Subscription[] = [
  {
    id: '1',
    name: 'Netflix Premium',
    provider: 'Netflix',
    amount: 17.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-01',
    category: 'streaming',
    lastUsed: '2026-03-19',
    status: 'active',
  },
  {
    id: '2',
    name: 'Adobe Creative Cloud',
    provider: 'Adobe',
    amount: 49.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-03-25',
    category: 'software',
    lastUsed: null,
    status: 'active',
  },
  {
    id: '3',
    name: 'Spotify Premium',
    provider: 'Spotify',
    amount: 10.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-04-05',
    category: 'streaming',
    lastUsed: '2026-03-20',
    status: 'active',
  },
  {
    id: '4',
    name: 'Amazon Prime',
    provider: 'Amazon',
    amount: 95.00,
    billingCycle: 'yearly',
    nextBillingDate: '2026-12-01',
    category: 'shopping',
    lastUsed: '2026-03-18',
    status: 'active',
  },
  {
    id: '5',
    name: 'Times Digital',
    provider: 'The Times',
    amount: 8.99,
    billingCycle: 'monthly',
    nextBillingDate: '2026-03-28',
    category: 'news',
    lastUsed: '2026-02-12',
    status: 'active',
  },
];

export default function SubscriptionsPage() {
  const [subscriptions, setSubscriptions] = useState(mockSubscriptions);
  const [selectedSub, setSelectedSub] = useState<Subscription | null>(null);
  const [generatedEmail, setGeneratedEmail] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  const totalMonthly = subscriptions
    .filter((s) => s.status === 'active')
    .reduce((sum, s) => {
      if (s.billingCycle === 'monthly') return sum + s.amount;
      return sum + s.amount / 12;
    }, 0);

  const handleCancelRequest = async (subscription: Subscription) => {
    setSelectedSub(subscription);
    setGenerating(true);
    setGeneratedEmail(null);

    // Simulate AI generation
    setTimeout(() => {
      const email = `Subject: Request to Cancel ${subscription.name} Subscription

Dear ${subscription.provider} Support Team,

I am writing to formally request the cancellation of my ${subscription.name} subscription.

Account Details:
- Service: ${subscription.name}
- Current billing: £${subscription.amount}/${subscription.billingCycle}
- Next billing date: ${new Date(subscription.nextBillingDate).toLocaleDateString('en-GB')}

I would like this cancellation to take effect immediately and would appreciate confirmation that no further charges will be made to my account after the current billing period ends.

Please confirm:
1. The effective date of cancellation
2. Any final charges (if applicable)
3. Confirmation that no further payments will be taken

As per the Consumer Contracts Regulations 2013, I expect this cancellation to be processed within 14 days and any refund for unused services to be processed within 14 days of cancellation.

Please send written confirmation of this cancellation to this email address.

Thank you for your assistance.

Yours sincerely,
[Your Name]
[Account Number/Email]

---
Generated by LifeAdminAI - UK Consumer Rights Assistant`;

      setGeneratedEmail(email);
      setGenerating(false);
    }, 2000);
  };

  const handleCopy = () => {
    if (generatedEmail) {
      navigator.clipboard.writeText(generatedEmail);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleConfirmCancel = (id: string) => {
    setSubscriptions((prev) =>
      prev.map((sub) => (sub.id === id ? { ...sub, status: 'pending_cancel' } : sub))
    );
    setSelectedSub(null);
    setGeneratedEmail(null);
  };

  return (
    <div className="max-w-7xl">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-white mb-2 flex items-center gap-3">
          <CreditCard className="h-10 w-10 text-amber-500" />
          Subscriptions
        </h1>
        <p className="text-slate-400">Manage and cancel subscriptions automatically</p>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-slate-900/50 backdrop-blur-sm border border-slate-800 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="bg-red-500/10 w-12 h-12 rounded-full flex items-center justify-center">
              <TrendingDown className="h-6 w-6 text-red-500" />
            </div>
          </div>
          <h3 className="text-3xl font-bold text-white mb-1">£{totalMonthly.toFixed(2)}</h3>
          <p className="text-slate-400 text-sm">Monthly spend</p>
        </div>

        <div className="bg-slate-900/50 backdrop-blur-sm border border-slate-800 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="bg-blue-500/10 w-12 h-12 rounded-full flex items-center justify-center">
              <CreditCard className="h-6 w-6 text-blue-500" />
            </div>
          </div>
          <h3 className="text-3xl font-bold text-white mb-1">
            {subscriptions.filter((s) => s.status === 'active').length}
          </h3>
          <p className="text-slate-400 text-sm">Active subscriptions</p>
        </div>

        <div className="bg-slate-900/50 backdrop-blur-sm border border-slate-800 rounded-2xl p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="bg-amber-500/10 w-12 h-12 rounded-full flex items-center justify-center">
              <Calendar className="h-6 w-6 text-amber-500" />
            </div>
          </div>
          <h3 className="text-3xl font-bold text-white mb-1">
            {subscriptions.filter((s) => !s.lastUsed || new Date(s.lastUsed) < new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)).length}
          </h3>
          <p className="text-slate-400 text-sm">Unused (30+ days)</p>
        </div>
      </div>

      {/* Subscriptions List */}
      <div className="space-y-4">
        {subscriptions.map((sub) => {
          const isUnused = !sub.lastUsed || new Date(sub.lastUsed) < new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
          const daysUntilBilling = Math.ceil(
            (new Date(sub.nextBillingDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
          );

          return (
            <div
              key={sub.id}
              className={`bg-slate-900/50 backdrop-blur-sm border rounded-2xl p-6 transition-all ${
                sub.status === 'pending_cancel'
                  ? 'border-amber-500/50 opacity-60'
                  : isUnused
                  ? 'border-red-500/30'
                  : 'border-slate-800'
              }`}
            >
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <h3 className="text-xl font-semibold text-white">{sub.name}</h3>
                    {isUnused && sub.status === 'active' && (
                      <span className="text-xs font-semibold text-red-400 bg-red-500/10 px-2 py-1 rounded">
                        Unused 30+ days
                      </span>
                    )}
                    {sub.status === 'pending_cancel' && (
                      <span className="text-xs font-semibold text-amber-400 bg-amber-500/10 px-2 py-1 rounded">
                        Pending Cancellation
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-6 text-sm text-slate-400 mb-3">
                    <span>£{sub.amount}/{sub.billingCycle === 'monthly' ? 'mo' : 'yr'}</span>
                    <span className="flex items-center gap-1">
                      <Calendar className="h-4 w-4" />
                      Next: {new Date(sub.nextBillingDate).toLocaleDateString('en-GB')}
                      {daysUntilBilling <= 7 && (
                        <span className="text-amber-400 ml-1">({daysUntilBilling} days)</span>
                      )}
                    </span>
                    {sub.lastUsed && (
                      <span>Last used: {new Date(sub.lastUsed).toLocaleDateString('en-GB')}</span>
                    )}
                  </div>

                  {sub.status === 'active' && (
                    <button
                      onClick={() => handleCancelRequest(sub)}
                      className="inline-flex items-center gap-2 bg-red-500/10 hover:bg-red-500/20 text-red-400 border border-red-500/30 px-4 py-2 rounded-lg transition-all text-sm font-medium"
                    >
                      <X className="h-4 w-4" />
                      Cancel Subscription
                    </button>
                  )}
                </div>

                <div className="text-right">
                  <div className="text-2xl font-bold text-white">
                    £{(sub.billingCycle === 'monthly' ? sub.amount : sub.amount / 12).toFixed(2)}
                  </div>
                  <div className="text-xs text-slate-500">per month</div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Cancellation Email Modal */}
      {selectedSub && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center p-6 z-50">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 max-w-2xl w-full max-h-[80vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                <Mail className="h-6 w-6 text-amber-500" />
                Cancellation Email
              </h2>
              <button
                onClick={() => {
                  setSelectedSub(null);
                  setGeneratedEmail(null);
                }}
                className="text-slate-400 hover:text-white"
              >
                <X className="h-6 w-6" />
              </button>
            </div>

            <div className="mb-6 bg-slate-950 rounded-lg p-4 border border-slate-800">
              <p className="text-sm text-slate-400 mb-2">
                Cancelling: <span className="text-white font-semibold">{selectedSub.name}</span>
              </p>
              <p className="text-sm text-slate-400">
                Savings: <span className="text-green-500 font-semibold">
                  £{(selectedSub.billingCycle === 'monthly' ? selectedSub.amount * 12 : selectedSub.amount).toFixed(2)}/year
                </span>
              </p>
            </div>

            {generating ? (
              <div className="text-center py-12">
                <div className="text-slate-400">Generating cancellation email...</div>
              </div>
            ) : generatedEmail ? (
              <>
                <div className="bg-slate-950 rounded-lg p-6 border border-slate-800 mb-6 max-h-96 overflow-y-auto">
                  <pre className="text-sm text-slate-300 whitespace-pre-wrap font-mono">
                    {generatedEmail}
                  </pre>
                </div>

                <div className="flex gap-3">
                  <button
                    onClick={handleCopy}
                    className="flex-1 flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-700 text-white py-3 rounded-lg transition-all"
                  >
                    {copied ? (
                      <>
                        <CheckCircle className="h-5 w-5" />
                        Copied!
                      </>
                    ) : (
                      <>
                        <Copy className="h-5 w-5" />
                        Copy Email
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => handleConfirmCancel(selectedSub.id)}
                    className="flex-1 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-slate-950 font-semibold py-3 rounded-lg transition-all"
                  >
                    Mark as Sent
                  </button>
                </div>
              </>
            ) : null}
          </div>
        </div>
      )}
    </div>
  );
}
