/**
 * Builder Proposal — Approve
 *
 * Founder clicks the Approve link from email/Telegram. We:
 *   1. Look up the proposal by token (one-time, not yet expired/used).
 *   2. Mark it 'approved'.
 *   3. Create a feature branch on GitHub (from master).
 *   4. Write each proposed file via the GitHub Contents API.
 *   5. Open a PR from the branch into master.
 *   6. Update the proposal with pr_number/pr_url, status='applied'.
 *   7. Comment on the originating ticket (if any) so support-triager sees it.
 *   8. Render a friendly HTML page confirming success (or showing failure).
 *
 * Auth: the token IS the auth. One-time. Expires after 24h. We refuse on:
 *   - missing/invalid token
 *   - already-approved/rejected/applied proposal
 *   - expired proposal
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export const runtime = 'nodejs';
export const maxDuration = 90;

const GITHUB_REPO = process.env.GITHUB_REPO || 'airpau/lifeadmin-ai';
const BASE_BRANCH = 'master';

function getAdmin() {
  return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);
}

function htmlPage(title: string, body: string, color = '#0B1220'): NextResponse {
  return new NextResponse(
    `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
<style>body{font-family:system-ui,sans-serif;max-width:560px;margin:48px auto;padding:24px;color:${color};line-height:1.55;}
.box{background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:24px;}
a{color:#059669;}</style></head>
<body>${body}</body></html>`,
    { headers: { 'content-type': 'text/html' } }
  );
}

interface ProposedFile {
  path: string;
  new_content: string;
}

interface Proposal {
  id: string;
  ticket_id: string | null;
  ticket_number: string | null;
  fix_type: string;
  summary: string;
  rationale: string;
  proposed_files: ProposedFile[];
  status: string;
  approval_token: string;
  created_at: string;
  expires_at: string;
}

async function ghFetch(path: string, init: RequestInit = {}): Promise<Response> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN env not configured');
  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      ...(init.headers || {}),
    },
  });
}

async function createBranchAndFiles(proposal: Proposal): Promise<{
  branchName: string;
  prNumber: number;
  prUrl: string;
}> {
  // 1. Get the latest commit SHA on master.
  const refRes = await ghFetch(`/repos/${GITHUB_REPO}/git/refs/heads/${BASE_BRANCH}`);
  if (!refRes.ok) throw new Error(`get master ref: ${refRes.status} ${(await refRes.text()).slice(0, 200)}`);
  const refData = (await refRes.json()) as { object: { sha: string } };
  const baseSha = refData.object.sha;

  // 2. Create a feature branch from that SHA.
  const slug = proposal.summary
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);
  const branchName = `builder/${slug}-${proposal.id.slice(0, 8)}`;
  const createRefRes = await ghFetch(`/repos/${GITHUB_REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });
  if (!createRefRes.ok && createRefRes.status !== 422) {
    throw new Error(`create branch: ${createRefRes.status} ${(await createRefRes.text()).slice(0, 200)}`);
  }

  // 3. Write each proposed file. The Contents API requires the current SHA when updating
  //    an existing file; for new files no SHA is needed.
  for (const file of proposal.proposed_files) {
    let existingSha: string | undefined;
    const getRes = await ghFetch(
      `/repos/${GITHUB_REPO}/contents/${encodeURIComponent(file.path)}?ref=${branchName}`
    );
    if (getRes.ok) {
      const data = (await getRes.json()) as { sha: string };
      existingSha = data.sha;
    }
    const putRes = await ghFetch(`/repos/${GITHUB_REPO}/contents/${encodeURIComponent(file.path)}`, {
      method: 'PUT',
      body: JSON.stringify({
        message: `Builder: ${proposal.summary} — ${file.path}`,
        content: Buffer.from(file.new_content, 'utf8').toString('base64'),
        branch: branchName,
        sha: existingSha,
      }),
    });
    if (!putRes.ok) {
      const errText = await putRes.text();
      throw new Error(`write ${file.path}: ${putRes.status} ${errText.slice(0, 200)}`);
    }
  }

  // 4. Open a PR.
  const prBody = [
    `**Auto-generated by the Builder managed agent.** Approved by founder via one-time token.`,
    ``,
    `**Fix type:** ${proposal.fix_type}`,
    proposal.ticket_number ? `**Triggering ticket:** ${proposal.ticket_number}` : null,
    ``,
    `## Why`,
    proposal.rationale,
    ``,
    `## Files changed (${proposal.proposed_files.length})`,
    proposal.proposed_files.map((f) => `- \`${f.path}\``).join('\n'),
    ``,
    `## Pre-merge checklist`,
    `- [ ] \`npx tsc --noEmit\` passes`,
    `- [ ] No DROP TABLE / ALTER TABLE DROP COLUMN`,
    `- [ ] No banned-integration imports (see CLAUDE.md \`03-tech-stack.md\`)`,
    `- [ ] No client-side API keys`,
    `- [ ] complaint_writer / riley-support-agent untouched`,
    ``,
    `_Builder proposal id: ${proposal.id}_`,
  ]
    .filter(Boolean)
    .join('\n');

  // Open PR as DRAFT so Vercel preview CI can run before founder is asked to merge.
  // builder-verify cron will poll the preview deployment; on READY it PATCHes the PR
  // to ready_for_review (and Telegrams the founder). On ERROR it closes the PR and
  // marks the proposal failed.
  const prRes = await ghFetch(`/repos/${GITHUB_REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({
      title: proposal.summary.slice(0, 250),
      head: branchName,
      base: BASE_BRANCH,
      body: prBody,
      draft: true,
    }),
  });
  if (!prRes.ok) throw new Error(`open PR: ${prRes.status} ${(await prRes.text()).slice(0, 200)}`);
  const prData = (await prRes.json()) as { number: number; html_url: string };

  return { branchName, prNumber: prData.number, prUrl: prData.html_url };
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const token = (searchParams.get('token') || '').trim();
  if (!token || !/^[a-f0-9]{64}$/.test(token)) {
    return htmlPage('Invalid token', `<div class="box"><h2>❌ Invalid token</h2><p>This approval link looks malformed. Make sure you used the link directly from your email or Telegram.</p></div>`);
  }

  const supabase = getAdmin();
  const { data: proposalRow, error } = await supabase
    .from('builder_proposals')
    .select('*')
    .eq('approval_token', token)
    .single();
  if (error || !proposalRow) {
    return htmlPage('Token not found', `<div class="box"><h2>❌ Token not found</h2><p>This approval link doesn't match any proposal. It may have been already used.</p></div>`);
  }
  const proposal = proposalRow as Proposal;

  if (proposal.status !== 'pending_review') {
    return htmlPage(
      'Already actioned',
      `<div class="box"><h2>ℹ️ Already actioned</h2><p>This proposal is already <strong>${proposal.status}</strong>. Each approval token is single-use.</p></div>`
    );
  }

  if (new Date(proposal.expires_at).getTime() < Date.now()) {
    await supabase
      .from('builder_proposals')
      .update({ status: 'expired' })
      .eq('id', proposal.id);
    return htmlPage('Expired', `<div class="box"><h2>⌛ Expired</h2><p>This proposal expired at ${proposal.expires_at}. Builder can re-propose it on the next pickup cycle.</p></div>`);
  }

  // Mark approved (state machine optimistic-locks: only update if still pending_review).
  const { data: updated, error: updErr } = await supabase
    .from('builder_proposals')
    .update({ status: 'approved', approved_by: 'founder', approved_at: new Date().toISOString() })
    .eq('id', proposal.id)
    .eq('status', 'pending_review')
    .select('id')
    .single();
  if (updErr || !updated) {
    return htmlPage(
      'Race condition',
      `<div class="box"><h2>⚠️ Already actioned by another tab</h2><p>Looks like this was just approved or rejected from another window.</p></div>`
    );
  }

  // Open the PR.
  let result: { branchName: string; prNumber: number; prUrl: string };
  try {
    result = await createBranchAndFiles(proposal);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    await supabase
      .from('builder_proposals')
      .update({ status: 'failed', last_error: msg })
      .eq('id', proposal.id);
    return htmlPage(
      'PR creation failed',
      `<div class="box"><h2>❌ PR creation failed</h2><p>The proposal was approved but creating the GitHub PR errored: <code>${msg.replace(/</g, '&lt;')}</code></p><p>Builder will pick this up again on the next cycle. Or you can retry manually with the same files.</p></div>`,
      '#dc2626'
    );
  }

  await supabase
    .from('builder_proposals')
    .update({
      status: 'applied',
      branch_name: result.branchName,
      pr_number: result.prNumber,
      pr_url: result.prUrl,
    })
    .eq('id', proposal.id);

  // Audit + notify the support_tickets row if there is one.
  await supabase.from('business_log').insert({
    category: 'recommendation',
    title: `Builder PR opened: #${result.prNumber} — ${proposal.summary.slice(0, 100)}`,
    content: `Approved by founder. PR ${result.prUrl}. Files: ${proposal.proposed_files.map((f) => f.path).join(', ')}. Triggering ticket: ${proposal.ticket_number ?? 'none'}.`,
    created_by: 'builder-agent',
  });

  if (proposal.ticket_id) {
    await supabase.from('ticket_messages').insert({
      ticket_id: proposal.ticket_id,
      sender_type: 'system',
      sender_name: 'Builder',
      message: `🛠️ Founder approved fix proposal. PR opened: ${result.prUrl}`,
    });
  }

  return htmlPage(
    'Approved & draft PR opened',
    `<div class="box">
      <h2>✅ Approved — draft PR opened</h2>
      <p>Branch: <code>${result.branchName}</code></p>
      <p>PR: <a href="${result.prUrl}" target="_blank" rel="noopener">#${result.prNumber}</a> <strong>(draft)</strong></p>
      <p>The PR is currently a <strong>draft</strong>. Vercel CI is running on the preview deployment. Within ~3-5 min:</p>
      <ul>
        <li>If CI <strong>passes</strong> → the PR is auto-promoted to ready-for-review and you'll get a Telegram + email ping to merge.</li>
        <li>If CI <strong>fails</strong> → the PR is auto-closed and Builder marks the proposal failed (you'll get a Telegram alert with the failure reason). Builder can re-iterate after the 4h cooldown with a different approach.</li>
      </ul>
      <p>You don't need to do anything right now.</p>
    </div>`,
    '#059669'
  );
}

export async function POST(req: NextRequest) {
  return GET(req);
}
