-- Phase 1: Dispute Threads + Correspondence Tracking
-- Transforms AI Letters from flat list to threaded conversations per company

-- ============================================================
-- 1. DISPUTES TABLE — one thread per company dispute
-- ============================================================
CREATE TABLE IF NOT EXISTS disputes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- Company / provider info
  provider_name TEXT NOT NULL,
  provider_type TEXT, -- energy, broadband, mobile, flight, parking, debt, retail, government, nhs
  account_number TEXT,

  -- Dispute details
  issue_type TEXT NOT NULL CHECK (issue_type IN (
    'complaint', 'energy_dispute', 'broadband_complaint', 'flight_compensation',
    'parking_appeal', 'debt_dispute', 'refund_request', 'hmrc_tax_rebate',
    'council_tax_band', 'dvla_vehicle', 'nhs_complaint'
  )),
  issue_summary TEXT NOT NULL, -- plain English description
  desired_outcome TEXT,
  disputed_amount DECIMAL(10, 2),
  currency TEXT DEFAULT 'GBP',

  -- Status tracking
  status TEXT NOT NULL CHECK (status IN (
    'open',              -- actively working on it
    'awaiting_response', -- sent letter, waiting for company reply
    'escalated',         -- gone to ombudsman/regulator
    'resolved_won',      -- got what we wanted
    'resolved_partial',  -- got something
    'resolved_lost',     -- didn't work out
    'closed'             -- user closed it
  )) DEFAULT 'open',

  -- Outcome
  money_recovered DECIMAL(10, 2) DEFAULT 0,
  outcome_notes TEXT,
  resolved_at TIMESTAMPTZ,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE disputes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own disputes"
  ON disputes FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own disputes"
  ON disputes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own disputes"
  ON disputes FOR UPDATE
  USING (auth.uid() = user_id);

-- Index for fast user lookups
CREATE INDEX IF NOT EXISTS idx_disputes_user_id ON disputes(user_id);
CREATE INDEX IF NOT EXISTS idx_disputes_status ON disputes(status);

-- ============================================================
-- 2. CORRESPONDENCE TABLE — every message in the thread
-- ============================================================
CREATE TABLE IF NOT EXISTS correspondence (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dispute_id UUID NOT NULL REFERENCES disputes(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,

  -- What type of entry is this?
  entry_type TEXT NOT NULL CHECK (entry_type IN (
    'ai_letter',       -- letter generated by Paybacker AI
    'company_email',   -- email received from the company
    'company_letter',  -- physical letter from the company (uploaded photo)
    'phone_call',      -- summary of a phone call
    'user_note',       -- user's own note or update
    'company_response' -- general response from company (pasted text)
  )),

  -- Content
  title TEXT, -- e.g. "Initial complaint letter", "Phone call with customer service"
  content TEXT NOT NULL, -- the actual text content
  summary TEXT, -- AI-generated summary for quick display

  -- File attachments (photos of letters, PDFs, etc.)
  attachments JSONB DEFAULT '[]', -- [{url, filename, type, size, uploaded_at}]

  -- Link to the AI-generated letter if entry_type = 'ai_letter'
  task_id UUID REFERENCES tasks(id) ON DELETE SET NULL,

  -- Metadata
  entry_date TIMESTAMPTZ DEFAULT NOW(), -- when this correspondence actually happened
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE correspondence ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own correspondence"
  ON correspondence FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own correspondence"
  ON correspondence FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own correspondence"
  ON correspondence FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own correspondence"
  ON correspondence FOR DELETE
  USING (auth.uid() = user_id);

-- Index for fast dispute thread lookups
CREATE INDEX IF NOT EXISTS idx_correspondence_dispute_id ON correspondence(dispute_id);
CREATE INDEX IF NOT EXISTS idx_correspondence_entry_date ON correspondence(entry_date);

-- ============================================================
-- 3. ADD dispute_id FK TO EXISTING TASKS TABLE
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'tasks' AND column_name = 'dispute_id'
  ) THEN
    ALTER TABLE tasks ADD COLUMN dispute_id UUID REFERENCES disputes(id) ON DELETE SET NULL;
    CREATE INDEX idx_tasks_dispute_id ON tasks(dispute_id);
  END IF;
END $$;

-- ============================================================
-- 4. FIX: Add 'approved' to tasks status CHECK constraint
--    (code already uses it but schema didn't include it)
-- ============================================================
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_status_check;
ALTER TABLE tasks ADD CONSTRAINT tasks_status_check CHECK (status IN (
  'pending_review', 'in_progress', 'awaiting_response',
  'resolved_success', 'resolved_partial', 'resolved_failed',
  'escalated', 'cancelled', 'approved', 'dismissed'
));
